#!/bin/bash
#BSUN -N

TYPE=$1
input_str=$2
cv_year=$3

module add R-4
module add gcc-8.3.0

mkdir -p /export/cluster-tmp/chenyehu

export TMPDIR=/export/cluster-tmp/chenyehu

# Rscript --vanilla tmp.R $input_str $cv_year

Rscript --vanilla main.R $input_str $cv_year $TYPE
